version: "3.8"

services: 
  web:
    build: .
    image: vehicle-data-explorer
    container_name: vehicle-data-explorer
    ports:
      - "8080:8080"
    environment: 
      - GIN_MODE=release
    depends_on:
      - redis_server
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2 
    ports:
      - "9200:9200"
    container_name: elasticsearch
    environment: 
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
  
  redis_server:
    image: redis:6.0.8
    container_name: redis
    ports: 
      - "6379:6379"

volumes:
  data01:
    driver: local